# Generated by Django 6.0.3 on 2026-03-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostepny', models.BooleanField(default=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'ordering': ['-data_dodania'],
            },
        ),
    ]
