# Generated by Django 6.0.3 on 2026-03-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mono', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('aktywna', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['nazwa'],
            },
        ),
        migrations.AddField(
            model_name='produkt',
            name='kategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produkty', to='app_mono.kategoria'),
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient_imie', models.CharField(max_length=100)),
                ('klient_email', models.EmailField(max_length=254)),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('nowe', 'Nowe'), ('w_realizacji', 'W realizacji'), ('zrealizowane', 'Zrealizowane'), ('anulowane', 'Anulowane')], default='nowe', max_length=20)),
                ('uwagi', models.TextField(blank=True)),
                ('suma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produkty', models.ManyToManyField(related_name='zamowienia', to='app_mono.produkt')),
            ],
            options={
                'verbose_name': 'Zamówienie',
                'verbose_name_plural': 'Zamówienia',
                'ordering': ['-data_zamowienia'],
            },
        ),
    ]
